# GoReleaser configuration for Homebrew Go
version: 2

project_name: homebrew-go

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: brew
    binary: brew
    main: ./cmd/brew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.FullCommit}}
      - -X main.BuildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - install.sh

checksum:
  name_template: 'checksums.txt'

# Upload install.sh as a standalone release asset
extra_files:
  - glob: install.sh

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other'
      order: 999



release:
  github:
    owner: pilshchikov
    name: homebrew-go
  prerelease: auto
  mode: replace
  header: |
    ## Homebrew Build {{ .Tag }}

    **Build Date:** {{ .Date }}
    **Commit:** {{ .ShortCommit }}

    This is an automated release of Homebrew Go.

  footer: >
    ## Installation Options

    ### Quick Install

    ```bash

    curl -sSL https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/install.sh | bash

    ```

    ### Custom Binary Name

    ```bash

    curl -sSL https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/install.sh | bash -s -- --name hbrew

    ```

    ### Manual Download

    Download from: https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/

    Built: {{ .Date }} | {{ .ShortCommit }}
