# GoReleaser configuration for Homebrew Go
version: 2

project_name: homebrew-go

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: brew
    binary: brew
    main: ./cmd/brew
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.FullCommit}}
      - -X main.BuildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE.txt
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other'
      order: 999



release:
  github:
    owner: pilshchikov
    name: homebrew-go
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## Homebrew Build {{ .Tag }}
    
    **Build Date:** {{ .Date }}  
    **Commit:** {{ .ShortCommit }}

    This is an automated release of Homebrew Go.

  footer: |
    ## 📦 Installation

    ### Download Binary Directly
    ```bash
    # macOS (Intel)
    curl -L https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/homebrew-go_Darwin_x86_64.tar.gz | tar xz
    
    # macOS (Apple Silicon)
    curl -L https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/homebrew-go_Darwin_arm64.tar.gz | tar xz
    
    # Linux (x86_64)
    curl -L https://github.com/pilshchikov/homebrew-go/releases/download/{{ .Tag }}/homebrew-go_Linux_x86_64.tar.gz | tar xz
    ```

    ### Install via Package Manager
    ```bash
    # Install from source with Go
    go install github.com/pilshchikov/homebrew-go/cmd/brew@{{ .Tag }}
    ```

    ## ✨ Automatic Build System

    This release was automatically generated with semantic version `{{ .Tag }}`.
    
    **Build Details:**
    - **Date:** {{ .Date | date "2006-01-02" }}
    - **Commit:** {{ .ShortCommit }}
    - **Build Number:** {{ .Env.GITHUB_RUN_NUMBER }}

  extra_files:
    - glob: ./docs/**/*
    - glob: ./scripts/**/*

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

announce:
  skip: "{{gt .Prerelease 1}}"